name: whim-server
version: '1.0.0'

ghc-options: -Wall

executables:
  whim-server:
    dependencies:
    - base
    - whim-server
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executables

library:
  dependencies:
  - base
  - classy-prelude
  - scotty
  - transformers
  - twilio
  source-dirs: library
