flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- aeson-1.2.0.0
- base-orphans-0.6
- bifunctors-5.2.1
- http-client-0.4.31.2
- http-client-tls-0.2.4.1
- primitive-0.6.2.0
- semigroupoids-5.2
- twilio-0.1.3.1
- vector-0.12.0.1
resolver: lts-8.15
